
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkvnuckiiuyqqaegzjtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rdm51Y2tpaXV5cXFhZWd6anR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTI0MzAsImV4cCI6MjA1OTE2ODQzMH0.fq11LOspc-F1JS6LLo0YL_M05pd_nkInQSdPdG2okb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'attendance-auth'
  }
});
